### ISSUE TITLE
Failed to activate the composer package

### ISSUE THREAD

**Issue by kadevland** [alairock/Composer-AtomEditor#11]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Debian GNU/Linux
**Thrown From**: [composer](https://github.com/alairock/Composer-AtomEditor) package, v0.5.0
### Stack Trace

Failed to activate the composer package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/kaosland/.atom/packages/composer/lib/composer.coffee:3:40)
    at Object.<anonymous> (/home/kaosland/.atom/packages/composer/lib/composer.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```
### Commands

```
  5x -4:02.6.0 click (atom-text-editor.editor.is-focused)
     -0:01.1.0 composer:about (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-dim-syntax"
    ],
    "packagesWithKeymapsDisabled": [
      "php-class-tree"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.7
autocomplete-sass, v0.1.0
bottom-dock, v0.3.5
color-picker, v2.0.13
composer, v0.5.0
css-snippets, v0.9.0
css-specificity, v0.2.0
emmet, v2.3.13
gulp-manager, v0.2.10
linter, v1.8.1
linter-csslint, v1.1.0
linter-htmlhint, v0.1.1
linter-jscs, v3.1.1
linter-jshint, v1.2.1
linter-manager, v0.2.3
linter-php, v1.0.5
linter-phpcs, v1.2.2
linter-write-good, v0.6.1
markdown-preview-plus, v2.2.2
mathjax-wrapper, v0.1.0
minimap, v4.13.4
minimap-autohide, v0.10.1
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.2
minimap-find-and-replace, v4.3.1
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
nucleus-dark-ui, v0.6.3
one-dark-dim-syntax, v0.1.0
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.1
php-extract-method, v0.2.0
pigments, v0.18.0
project-manager, v2.6.4
sass-autocompile, vundefined

# Dev
No dev packages
```

**Comment by zimme** [comment]
Uninstall the package, quit atom, remove `~/.atom/.apm/composer` and `~/.atom/.apm/atom-message-panel`. Install `composer` package again and see if that works.

**Comment by zimme** [comment]
Closing this due to inactivity, @mention me if this isn't resolved.
