### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by soovorow** [alairock/Composer-AtomEditor#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [composer](https://github.com/alairock/Composer-AtomEditor) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'apply' of undefined

```
At C:\Users\asus\.atom\packages\composer\lib\main.coffee:45

TypeError: Cannot read property 'apply' of undefined
    at /packages/composer/lib/main.coffee:45:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1179:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:37.9.0 core:confirm (input.hidden-input)
     -3:24.6.0 core:select-all (input.hidden-input)
     -2:56.5.0 core:confirm (input.hidden-input)
     -1:36.4.0 core:select-all (input.hidden-input)
     -1:35.1.0 core:confirm (input.hidden-input)
     -0:50.8.0 composer:update (input.hidden-input)
     -0:20.4.0 composer:version (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
```

### Non-Core Packages

```
composer 0.5.0 
darcula-syntax 0.2.1 
```

**Comment by Monotoba** [comment]
Same Issue on Ubuntu 14.04 with most recent updates installed
